### ISSUE TITLE
Project still alive? Wrong XML structure: cannot parse data

### ISSUE THREAD

**Issue by Rourke101** [savon-noir/python-libnmap#105]
I am getting a 

`libnmap.parser.NmapParserException: Wrong XML structure: cannot parse data`

So I can imagine the library is not updated to the latest versions... Is the project still alive?

**Comment by BastienFaure** [comment]
@savon-noir I'm more than happy to contribute if you want to add me as a collaborator :)

**Comment by savon-noir** [comment]
@Rourke101 @BastienFaure help will be most welcome. I'm now cleaning up the code and reviewing all current issues but first i wanted to automate as much as possible to reduce the maintenance tasks to its minimum.

I could then create a small organisation so the repo is off my personal account to easily enable new collaborators.

In the meantime, could you please share an example of a "unsupported file"?

**Comment by BastienFaure** [comment]
@savon-noir whatever works the best for you. Feel free to create an org but I guess you could also just add people as collaborators to this personal repository ? As a volunteer I'd just like being able to close issues/PR, push changes etc.

Thanks !

**Comment by savon-noir** [comment]
@Rourke101 I've tried a full scan with all the funkiness enabled (nse scripts, traceroute, OS fp, banner grabbing,...) on a set of honeypots with latest nmap release. resulting xml file could be parsed without throwing that exception. I'll close the issue in a few weeks if I have no further feedback.

**Comment by savon-noir** [comment]
@BastienFaure I'd like first to rebase a bit this work to make it ready for improvements/validation and ship some contributions guidelines.  Because so far, most of the PR I got would not pass the travis-ci or were not provided with unittest sets.
I've been working now on code formatting, fixing  the CVE issue and test framework. I'll step by step go through the different issues + PR and close them. 
I would be happy to onboard a new contributor but maybe we should first work a bit together since i'd like to keep an approval right on pushes in master branch and certainly in the pypi repo for now. But of course, at the end, the idea is to open the project to other contributors. 
So if you have some features you'd like to have baked in or features, w can start working together with the classical PR approach and later consider to add you as collab. I'll be also more reactive to PR :p

**Comment by savon-noir** [comment]
closed for inactivity.
